### ISSUE TITLE
Need some help with compilation

### ISSUE THREAD

**Issue by yyarmoshyk** [rpatrick00/terraform-provider-environment#2]
I get the following error when running make:
```
make
go vet .
can't load package: package _/terraform-provider-environment: cannot find package "_/terraform-provider-environment" in any of:
        /usr/local/go/src/_/terraform-provider-environment (from $GOROOT)
        /go/src/_/terraform-provider-environment (from $GOPATH)
can't load package: package _/terraform-provider-environment/environment: cannot find package "_/terraform-provider-environment/environment" in any of:
        /usr/local/go/src/_/terraform-provider-environment/environment (from $GOROOT)
        /go/src/_/terraform-provider-environment/environment (from $GOPATH)

Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make: *** [Makefile:31: vet] Error 1
```

I used the default golang docker image for build:
`docker run -v $(pwd):/terraform-provider-environment -w /terraform-provider-environment -t golang make`

**Comment by rpatrick00** [comment]
This is due to the way that Go works with import references.  It expects to be able to resolve all references in the source code files' import section to the src subdirectory of a location in the GOPATH (or under the Go installation directory).  If you are going to compile inside this container, you need to make sure all of the necessary directories are resolvable.

At the time I wrote this provider, I had to have the terraform git repository available to compile this plugin.  Since that time, a new terraform-plugin-sdk project has emerged which is probably a better way to handle this.  I haven't had time to look into making these changes.  If you get it working, feel free to send a PR.
